development: &default
  adapter: postgresql
  database: administrate-prototype_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  host: 127.0.0.1
  port: 5432
  user: postgres

test:
  <<: *default
  database: administrate-prototype_test
